Install correct version of Airflow
I noticed that the job `hatch run tests.py3.13-3.0:test`:wq was failing in the CI with several errors:

```
FAILED tests/operators/test_fivetran.py::TestFivetranOperator::test_fivetran_operator_get_openlineage_facets_on_start - ImportError: cannot import name 'DocumentationJobFacet' from 'fivetran_provider_async' (/Users/tatiana.alchueyr/Code/airflow-provider-fivetran-async/fivetran_provider_async/__init__.py)
FAILED tests/utils/test_operator_utils.py::TestFivetranUtils::test_utils_get_fields_destination - ImportError: cannot import name 'SchemaDatasetFacet' from 'fivetran_provider_async' (/Users/tatiana.alchueyr/Code/airflow-provider-fivetran-async/fivetran_provider_async/__init__.py)
FAILED tests/utils/test_operator_utils.py::TestFivetranUtils::test_utils_get_fields_source - ImportError: cannot import name 'SchemaDatasetFacet' from 'fivetran_provider_async' (/Users/tatiana.alchueyr/Code/airflow-provider-fivetran-async/fivetran_provider_async/__init__.py)
FAILED tests/utils/test_operator_utils.py::TestFivetranUtils::test_utils_input_dataset - ImportError: cannot import name 'Dataset' from 'fivetran_provider_async' (/Users/tatiana.alchueyr/Code/airflow-provider-fivetran-async/fivetran_provider_async/__init__.py)
FAILED tests/utils/test_operator_utils.py::TestFivetranUtils::test_utils_output_dataset - ImportError: cannot import name 'Dataset' from 'fivetran_provider_async' (/Users/tatiana.alchueyr/Code/airflow-provider-fivetran-async/fivetran_provider_async/__init__.py)
```

I was albe to reproduce locally and noticed that the problem is that  hatch matrix specifies airflow = ["3.0"], and pre-install-airflow.sh installs apache-airflow==3.0 with constraints. But then
  hatch installs the project dependencies (which only require apache-airflow>=2.4.0), and the resolver is free to upgrade Airflow to 3.2.0.

This PR aims to solve this